version: '3.8'

services:
  # Container do PostgreSQL
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: dotta
      POSTGRES_PASSWORD: safepass
      POSTGRES_DB: processamento_pedidos
      # POSTGRES_DB: meu_db # Opcional: Cria um database com nome específico na inicialização
      # POSTGRES_USER: meu_user # Opcional: Cria um usuário customizado (o padrão é 'postgres')
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persiste os dados mesmo se o container for removido
    networks:
      - processamento_pedidos

# Define os volumes para persistência de dados
volumes:
  postgres_data:
# Definição de uma rede comum para que os containers se "enxerguem" pelo nome